Repository ParkGeonRyul/Eden-Front, pull requests merged in 2024-02, with the labels that each got.

#24 🐛 fix : Admin 상세페이지 UI 추가 수정 완료
  src/app/admin-list-detail-page/adminListDetailPage.style.ts
Labels: 리뷰완료~

#22 ✨ feat : mypage UI publishing
  package-lock.json
  package.json
  public/mock/mypageInfo.json
  public/mock/sidebarCategory.js
  public/mock/userInquiry.json
  src/app/mypage/edit/edit.style.ts
  src/app/mypage/edit/page.tsx
  src/app/mypage/info.style.ts
  src/app/mypage/inquiry/inquiry.style.ts
  src/app/mypage/inquiry/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/assets/icons/goKey.svg
  src/assets/icons/myInquiry.svg
  src/components/Mypage/Info/BasicInfoSection/BasicInfoSection.tsx
  src/components/Mypage/Info/BasicInfoSection/basicInfoSection.style.ts
  src/components/Mypage/Info/ProfileInfoSection/ProfileInfoSection.tsx
  src/components/Mypage/Info/ProfileInfoSection/profileInfoSection.style.ts
  src/components/Mypage/Inquiry/InquiryDetail/InquiryDetail.tsx
  src/components/Mypage/Inquiry/InquiryDetail/inquiryDetail.style.ts
  src/components/Mypage/Inquiry/InquiryList/InquiryListItem.tsx
  src/components/Mypage/Inquiry/InquiryList/inquiryListItem.style.ts
  src/components/Mypage/SideNav/sidenav.style.ts
  src/components/Mypage/SideNav/sidenav.tsx
  src/components/common/Button/CommonButton/commonButton.style.ts
  src/components/icons/index.ts
  src/types/apis/userInfo.ts
  src/types/apis/userInquiry.ts
Labels: 리뷰완료~, review

#26 ♻️ refactor : mypage UI (이전 pr 리뷰 반영)
  src/app/mypage/edit/edit.style.ts
  src/app/mypage/edit/page.tsx
  src/app/mypage/info.style.ts
  src/app/mypage/inquiry/inquiry.style.ts
  src/app/mypage/inquiry/page.tsx
  src/app/mypage/page.tsx
  src/components/Mypage/Info/basicInfoConstants.ts
  src/types/apis/userInfo.ts
Labels: 리뷰완료~

#17 ✨ feat : 리뷰 적용 및 모달공용컴포넌트 도입
  public/mock/inquiry.json
  src/app/inquiry/inquiryModal.style.ts
  src/app/inquiry/page.tsx
  src/app/inquiry/post/page.tsx
  src/app/inquiry/post/post.style.ts
  src/app/inquiry/searchModal.style.ts
  src/assets/icons/mail.svg
  src/components/CheckBox/CheckBox.tsx
  src/components/DropDown/DropDown.tsx
  src/components/icons/index.ts
Labels: 리뷰완료~, review

#31 ✨ feat: mypage modal UI (리뷰 반영)
  src/app/mypage/edit/page.tsx
  src/assets/icons/modalCloseButton.svg
  src/components/Mypage/Info/BasicInfoSection/BasicInfoSection.tsx
  src/components/common/Modal/AddressModal/AddressModal.tsx
  src/components/common/Modal/AddressModal/addressModal.style.ts
  src/components/common/Modal/EmailAuthModal/EmailAuthModal.tsx
  src/components/common/Modal/EmailAuthModal/emailAuthModal.style.ts
  src/components/icons/index.ts
Labels: review

#30 ✨ feat : 메인타이틀 목데이터 값 확인(리뷰반영)
  package-lock.json
  package.json
  public/mock/mainTitle.json
  src/app/home.style.ts
  src/app/inquiry/page.tsx
  src/app/page.tsx
  src/types/apis/mainTitle.ts
Labels: review

#36 ✨feat: view counter button [리뷰 반영]
  public/mock/viewCount.json
  src/assets/icons/arrowUp.svg
  src/components/common/ViewCount/ViewCount.tsx
  src/components/common/ViewCount/ViewCountDropdown/ViewCountDropDown.tsx
  src/components/common/ViewCount/ViewCountDropdown/viewCountDropDown.style.ts
  src/components/common/ViewCount/utils/formatViewData.ts
  src/components/common/ViewCount/utils/outsideClick.ts
  src/components/common/ViewCount/viewCount.style.ts
  src/components/icons/ArrowUpIcon.tsx
  src/components/icons/index.ts
  src/types/apis/viewCount.ts
  src/types/components/viewCount.d.ts
Labels: 리뷰완료~, review

#35 ✨ feat: list posts and edit page UI[리뷰 반영 + conflict 해결]
  public/mock/petsListItem.json
  public/mock/postData.json
  src/app/list/[slug]/[id]/edit/page.tsx
  src/app/list/[slug]/[id]/listDetail.style.ts
  src/app/list/[slug]/[id]/page.tsx
  src/app/list/[slug]/list.style.ts
  src/app/list/[slug]/new/page.tsx
  src/app/list/[slug]/page.tsx
  src/components/FormPage/Container/FormPageContainer.tsx
  src/components/FormPage/UI/FilesInput/FilesInput.tsx
  src/components/FormPage/UI/FilesInput/filesInput.style.ts
  src/components/FormPage/UI/FormButton/FormButton.tsx
  src/components/FormPage/UI/FormButton/formButton.style.ts
  src/components/FormPage/UI/FormPage.tsx
  src/components/FormPage/UI/formPage.style.ts
  src/components/FormPage/utils/getCategoryTypeFromSlug.ts
  src/components/FormPage/utils/postValid.ts
  src/components/FormPage/utils/updatdFormData.ts
  src/interfaces/listPage.ts
  src/types/apis/listItem.ts
  src/types/components/formTypes.d.ts
Labels: review

#41 ♻️ refactor : 유효성 검사 로직 함수 분리, 타입 분리[리뷰적용]
  src/app/inquiry/page.tsx
  src/components/Modal/InquiryModal/InquiryModal.tsx
  src/components/Modal/SearchModal/SearchModal.tsx
  src/components/Modal/SearchModal/searchModal.style.ts
  src/types/apis/inquiryData.ts
  src/utils/inquiry/validateInquiryData.ts
Labels: review

#48 ✨feat : Add pagination component in list [ 리뷰반영 ]
  next.config.js
  public/mock/listDetail.json
  public/mock/listDetails.json
  public/mock/petsListItem.json
  public/mock/postData.json
  src/app/list/[slug]/[id]/edit/page.tsx
  src/app/list/[slug]/[id]/page.tsx
  src/app/list/[slug]/layout.tsx
  src/app/list/[slug]/list.style.ts
  src/app/list/[slug]/page.tsx
  src/assets/icons/pagination/arrowLeft.svg
  src/assets/icons/pagination/arrowRight.svg
  src/components/FormPage/Container/FormPageContainer.tsx
  src/components/ListDetail/UI/ListDetailPage.tsx
  src/components/ListDetail/UI/listDetailPage.style.ts
  src/components/ListPage/PageButton/PageButton.tsx
  src/components/ListPage/PageButton/pageButton.style.ts
  src/components/common/MainPage/mainPage.style.ts
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/pagination.style.ts
  src/components/icons/index.ts
  src/interfaces/listPage.ts
  src/types/apis/listItem.ts
Labels: review
